Positioning-and-Floating-Elements
tiagoes/Positioning-and-Floating-Elements pull request #2
Opened 2020-06-23 14:20 UTC by tiagoes

Please kindly review our project

2020-06-23 17:18 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🚨

## Hello @tiagoes and @GraceOyiza 🖐. Impressive project 👏🙌!

### However, we need to work on some changes before we can merge.

- Remember to add a descriptive PR, like, what you have done in this project, etc....
- There are webhint and stylelint errors. Remember to fix these errors before submitting for code review.

![image](https://user-images.githubusercontent.com/57726348/85432025-f7cc2480-b59f-11ea-86f0-b02ff0a14712.png)

![image](https://user-images.githubusercontent.com/57726348/85432312-6ad59b00-b5a0-11ea-976e-8bce4fa4a104.png)

- The social icons and some texts are overlapping with the top navbar.

![image](https://user-images.githubusercontent.com/57726348/85431877-c3586880-b59f-11ea-8796-36ceac0c99c9.png)

- The NY Times logo must be a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))

- There is extra space below the footer.

#### Clone
![image](https://user-images.githubusercontent.com/57726348/85433298-d9ffbf00-b5a1-11ea-97cd-8efdb847b262.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/85433524-306cfd80-b5a2-11ea-9126-96774b553889.png)

- The fixed footer is missing.

#### Clone
![Annotation 2020-06-23 224234](https://user-images.githubusercontent.com/57726348/85434001-fbad7600-b5a2-11ea-91cd-bace819eba6a.jpg)

#### Original
![Annotation 2020-06-23 224307](https://user-images.githubusercontent.com/57726348/85434026-0536de00-b5a3-11ea-86f2-ffc1b40ee7d6.jpg)

- Your CSS file has one invalid property. Check the comments below.

2020-06-23 17:19 UTC, tirthajyoti-ghosh commented on styles/index.css
> +  width: 1 2.5%;
`width` only takes one value.

2020-06-23 17:21 UTC, tirthajyoti-ghosh reviewed
Your project is really amazing! You guys have done an incredible job. 
Before you submit any project for review be sure to fix all the stylelint errors.

Apply these changes and request another review.

Happy coding 👨‍💻

2020-06-25 08:46 UTC, tiagoes commented
All the necessaries changes have been done.
Please review our code again.

2020-06-25 10:31 UTC, andresporras3423 commented
### **Pull Request Under Review By Oscar Russi (TSE)**

2020-06-25 10:37 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @tiagoes @GraceOyiza** 
Good job with this new submission for this project :muscle:  
Your page really looks like a clone of the original :clap: :clap: :clap:  
Your project passes most of the requirements. There are just a few details to improve before you can go ahead:
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition (in your CSS files).

### OPTIONAL

- [ ] your footer tag should be outside your main tag and it should be the last element in your HTML

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-06-25 10:37 UTC, andresporras3423 commented on styles/index.css
> +}
This selector has the same style definition of selectors on lines 169 and 196. Group selectors to minimize your code.

2020-06-26 02:38 UTC, tiagoes commented
All the necessaries changes have been done.
Please review our code again.

2020-06-26 02:50 UTC, christianotieno approved these changes
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  Keep it up.
##
### The [clone](https://raw.githack.com/tiagoes/Positioning-and-Floating-Elements/main-branch/index.html) shows good understanding and usage of the positioning and floating of elements. 💯 
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README.md and is professionally done. Good job with that.
- Pull Request has a meaningful title and a short description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @tiagoes  & @GraceOyiza! :+1:
- You can now merge these changes. 
- I wish you all the very best in your next tasks 🥇 
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

2020-07-01 11:37 UTC, merged